### ISSUE TITLE
Handle emit events when app is in foreground

### ISSUE THREAD

**Issue by antonio-ivanovski** [toteto/react-native-background-job#3]
Currently the job trigger event is only handled when the app is in background.

**Comment by antonio-ivanovski** [comment]
@bevkoski could you look into https://github.com/toteto/react-native-background-job/commit/fe5c55e3ccc998f41a7fa78d208ec9a95053f483 and see if this is the proper way to handle emit events.

The event is emitted via: https://github.com/toteto/react-native-background-job/blob/master/android/src/main/java/com/pilloxa/backgroundjob/ReactNativeEventStarter.java#L44

**Comment by bevkoski** [comment]
@toteto, I took a look at it and I think that the library should not emit events or add listeners for events.
`DeviceEventEmitter` is a React Native method for adding listeners to events. Usually, we attach listeners on `componentDidMount`, when the app comes into view. It is also very important to remove listeners with `listener.remove()` and we usually do this on `componentWillUnmount`.
The problem here is that the library never releases the listeners because it does not have knowledge about the mounting and un-mounting of the app.
My suggestion is not to emit events or add listeners, which is the current behaviour of the official branch of the library.
